apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: anam
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: anam
    app.kubernetes.io/part-of: byoc-app-hlph
  name: anam
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: anam
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: anam
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/byoc-chwh-tenant/byoc-app-hlph/anam@sha256:f6b545250c43370836674969c4ab2ab5d4deca181effb627916f52085e38ef68
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
