apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: anam
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: anam
    app.kubernetes.io/part-of: byoc-app-hlph
  name: anam
spec:
  rules:
  - host: anam-byoc-chwh-tenant.apps.e45724785c64abcc44d9.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: anam
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
